services:
  app:
    build: .
    image: hl_etl:latest
    container_name: hl_etl_service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
    command: ["uv", "run", "python3", "main.py"]
    restart: always

  db:
    image: postgres:18.0-alpine3.22
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: hl_etl_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: always

volumes:
  pgdata:
