CREATE TABLE IF NOT EXISTS vaults (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vault_address VARCHAR(42) UNIQUE NOT NULL,
  name VARCHAR(255),
  -- Performance
  apr DECIMAL(18,8),                                 -- проценты
  total_pnl_usd DECIMAL(38,18),
  total_pnl_percent DECIMAL(18,8),                   -- проценты
  monthly_account_value_change DECIMAL(18,8),        -- проценты
  weekly_account_value_change DECIMAL(18,8),         -- проценты
  win_days_ratio DECIMAL(18,8),                      -- проценты
  -- Risk
  max_drawdown DECIMAL(18,8),                        -- проценты
  current_drawdown DECIMAL(18,8),                    -- проценты
  daily_volatility DECIMAL(18,10),                   -- доли (стд. откл. дневных доходностей)
  sharpe_ratio DECIMAL(18,10),
  average_recovery_days DECIMAL(18,8),
  -- Trading
  daily_volume DECIMAL(38,18),
  trades_per_day DECIMAL(18,8),
  average_trade_size DECIMAL(38,18),
  average_position_holding_time DECIMAL(18,8),       -- часы
  top_token_volume_share DECIMAL(18,8),              -- проценты
  -- Trend
  seven_day_change DECIMAL(18,8),                    -- проценты
  thirty_day_change DECIMAL(18,8),                   -- проценты
  momentum_score DECIMAL(18,10),
  days_since_ath INTEGER,
  consecutive_positive_days INTEGER,
  -- Capital
  tvl DECIMAL(38,18),
  follower_count INTEGER,
  average_investment_per_follower DECIMAL(38,18),
  vault_age_days INTEGER,
  leader_commission_rate DECIMAL(18,8),              -- доли (0..1)
  -- Efficiency
  average_pnl_per_trade DECIMAL(38,18),
  profit_factor DECIMAL(18,10),
  return_to_drawdown_ratio DECIMAL(18,10),           -- вместо risk_adjusted_return
  capital_efficiency DECIMAL(18,8),                  -- проценты
  last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);